new_id: 4
_core:
  default_config_hash: 1qKVk03zhLAZj-W36dakmXWDO3mx28TRgx9iDzHpqMs
callback_1:
  created: 1622013334
  cid: 1
  updated: 1622013334
  path: /mainpage
  page_title: Homepage
callback_2:
  created: 1622033778
  cid: 2
  updated: 1622033778
  path: /about
  page_title: 'About Us'
callback_3:
  created: 1622034011
  cid: 3
  updated: 1622034011
  path: /contact-us
  page_title: 'Contact us'
